# Versão do Docker Compose
version: '3.8'

# ==============================================================================
# 🐳 ARQUIVO DE CONFIGURAÇÃO DOCKER COMPOSE – PROJETO ATLAS
#
# Este arquivo define os serviços, redes e volumes para o ambiente de
# desenvolvimento local do Atlas, utilizando Supabase para banco de dados
# e armazenamento de objetos.
#
# Para iniciar os serviços locais:
# $ docker-compose up -d
#
# Para parar os serviços:
# $ docker-compose down
# ==============================================================================

services:
  # --- BANCO DE DADOS DE GRAFO (LOCAL) ---
  neo4j:
    image: neo4j:5.13 # Imagem oficial do Neo4j
    container_name: atlas_neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/atlas_password # Usuário/senha
    ports:
      - "7474:7474" # Interface HTTP
      - "7687:7687" # Porta Bolt para conexão de drivers
    volumes:
      - neo4j_data:/data
    networks:
      - atlas_net

  # --- API DE CONSULTA (LOCAL) ---
  api:
    build:
      context: ./src/api
    container_name: atlas_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    networks:
      - atlas_net

  # --- WORKER DE INGESTÃO/ETL (LOCAL) ---
  # Este worker agora se conecta ao Supabase, conforme definido no .env
  worker:
    build:
      context: .
      dockerfile: src/worker/Dockerfile
    container_name: atlas_worker
    env_file:
      - .env
    depends_on:
      - neo4j
    networks:
      - atlas_net
    # As variáveis de ambiente para conexão com o banco de dados
    # são lidas a partir do arquivo .env pelos próprios scripts.

# --- VOLUMES PARA PERSISTÊNCIA DE DADOS (APENAS SERVIÇOS LOCAIS) ---
volumes:
  neo4j_data:
    driver: local

# --- REDE PARA COMUNICAÇÃO ENTRE SERVIÇOS LOCAIS ---
networks:
  atlas_net:
    driver: bridge
